name: bwu_utils
version: 0.1.0-dev.2
description: A collection of utilities.
homepage: https://github.com/bwu-dart/bwu_utils
author: Günter Zöchbauer <guenter@gzoechbauer.com>
environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  args: '>=0.13.0 <0.14.0'
  grinder:
    git: git@github.com:google/grinder.dart.git
  path: '>=1.0.0 <2.0.0'
  quiver: '>=0.21.3 <0.22.0'
  quiver_log: '>=1.0.3 <2.0.0'
  webdriver: '>=0.10.0-pre.2 <0.11.0'

dev_dependencies:
  test: #'>=0.12.0-beta.10 < 0.13.0'
    git: git@github.com:dart-lang/test.git
  dart_style: '>=0.1.7 <0.2.0'
  # remove dependeny when lib/grinder/linter_task.dart is removed
  linter:
    git: git@github.com:dart-lang/linter.git
  polymer: '>=0.16.1+4 <0.17.0'

dependency_overrides:
  args: '>=0.13.0 <0.14.0'
  analyzer: '>=0.25.0-dev.2 <0.26.0' # for grinder analyze task
  matcher: '>=0.12.0-alpha.0 < 0.13.0'
  test: #'>=0.12.0-beta.10 < 0.13.0'
    git: git@github.com:dart-lang/test.git

transformers:
- test/pub_serve:
    $include: test/browser/**_test.dart

- polymer:
    entry_points:
    - test/browser/html_test.html
    - test/testing/webdriver/polymer/index.html

