name: bwu_utils
version: 0.1.0-dev.2
description: A collection of utilities.
homepage: https://github.com/bwu-dart/bwu_utils
author: Günter Zöchbauer <guenter@gzoechbauer.com>
environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  args: '>=0.13.0 <0.14.0'
  bwu_utils_dev: #'>=0.1.0 <0.2.0'
    path: ../bwu_utils_dev
  html: '>=0.12.1 <0.13.0'
  logging: '>=0.9.0 <0.11.0'
  path: '>=1.0.0 <2.0.0'
  quiver: '>=0.21.3 <0.22.0'
  quiver_log: '>=1.0.3 <2.0.0'

dev_dependencies:
  grinder: '>=0.7.0-dev.1 <0.8.0'
    # git: git@github.com:google/grinder.dart.git
   # git: git@github.com:dart-lang/test.git
  polymer: '>=0.16.1+4 <0.17.0'
  test: '>=0.12.0-rc.0 < 0.13.0'

dependency_overrides:
  args: '>=0.13.0 <0.14.0'
  analyzer: '>=0.25.0-dev.2 <0.26.0' # for grinder analyze task
  matcher: '>=0.12.0-alpha.0 < 0.13.0'
#  test: #'>=0.12.0-beta.10 < 0.13.0'
#    git: git@github.com:dart-lang/test.git

transformers:
- polymer:
    entry_points:
    - test/browser/polymer_test_example/jhtml_test.html
    - test/testing/webdriver/polymer/index.html

- test/pub_serve:
    $include: test/**_test{.*,}.dart
