name: bwu_utils
version: 0.0.2
description: utils that depend neither on 'dart:io' nor 'dart:html'
homepage: https://github.com/bwu-dart/bwu_utils
author: Günter Zöchbauer <guenter@gzoechbauer.com>
environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  unittest: any