name: bwu_utils
version: 0.1.0-dev.1
description: A collection of utilities.
homepage: https://github.com/bwu-dart/bwu_utils
author: Günter Zöchbauer <guenter@gzoechbauer.com>
environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  grinder:
    git: git@github.com:google/grinder.dart.git
  path: '>=1.0.0 <2.0.0'
  quiver: '>=0.21.3 <0.22.0'
  quiver_log: '>=1.0.3 <2.0.0'
dev_dependencies:
  unittest: any
  dart_style: '>=0.1.7 <0.2.0'
  linter:
    git: git@github.com:dart-lang/linter.git
dependency_overrides:
#  analyzer: '>=0.24.0 <0.25.0' # for grinder analyze task
