name: bwu_utils
version: 0.1.0-dev.3
description: A collection of utilities.
homepage: https://github.com/bwu-dart/bwu_utils
author: Günter Zöchbauer <guenter@gzoechbauer.com>
environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  args: '>=0.13.0 <0.14.0'
  html: '>=0.12.1 <0.13.0'
  logging: '>=0.9.0 <0.12.0'
  path: '>=1.0.0 <2.0.0'
  quiver: '>=0.21.3 <0.22.0'
  quiver_log: '>=1.0.3 <2.0.0'

dev_dependencies:
  bwu_utils_dev: '^0.1.0-dev.5'
  polymer: '>=0.16.1+4 <0.17.0'
  test: '>=0.12.0 <0.13.0'

dependency_overrides:

transformers:
- test/pub_serve:
    $include: test/**_test{.*,}.dart
